CREATE OR REPLACE TABLE CUSTOMER_OFFERINGS (
    CUSTOMER_ID STRING,
    SITE_ID STRING,
    OFFERINGS STRING,
    OFFERING_PRICE NUMBER,
    OFFERINGS_EUC NUMBER,
    OFFERING_TYPE STRING,
    POTENTIAL_OFFERING_LEVEL_INVESTMENT NUMBER,
    PRODUCT_CODE STRING,
    PRODUCTS_EUC NUMBER,
    PRODUCT_UNIT_PRICE NUMBER,
    CSA VARIANT,
    SAVINGS VARIANT
);
 


 INSERT INTO bic.bic_schema.CUSTOMER_OFFERINGS (
    CUSTOMER_ID, SITE_ID, OFFERINGS, OFFERING_PRICE, OFFERINGS_EUC, OFFERING_TYPE,
    POTENTIAL_OFFERING_LEVEL_INVESTMENT, PRODUCT_CODE, PRODUCTS_EUC, PRODUCT_UNIT_PRICE, CSA, SAVINGS)
SELECT
    'Vishal Super Market', 'BN001','KITCHEN SPECIALTY',20,COALESCE(MAX(OFFERINGS_EUC), 0) + 1,'Service',34,
    'Super Natural Stain remover' ,COALESCE(MAX(PRODUCTS_EUC), 0) + 1,2,
    PARSE_JSON('{"Room Count": "100", "sqft": "10000"}'),
    PARSE_JSON('{"Water Savings": "100", "Energy Savings": "10000"}')
FROM bic.bic_schema.CUSTOMER_OFFERINGS;

 INSERT INTO bic.bic_schema.CUSTOMER_OFFERINGS (
    CUSTOMER_ID, SITE_ID, OFFERINGS, OFFERING_PRICE, OFFERINGS_EUC, OFFERING_TYPE,
    POTENTIAL_OFFERING_LEVEL_INVESTMENT, PRODUCT_CODE, PRODUCTS_EUC, PRODUCT_UNIT_PRICE, CSA, SAVINGS)
SELECT
    'Vishal Super Market', 'BN001','KITCHEN SPECIALTY',20,COALESCE(MAX(OFFERINGS_EUC), 0) + 1,'Asset-Boiler',34,
    'Super Natural Stain remover' ,COALESCE(MAX(PRODUCTS_EUC), 0) + 1,2,
    PARSE_JSON('{"Boiler Count": "100", "Size A": "2", "Size B": "2"}'),
    PARSE_JSON('{"Water Savings": "100", "Energy Savings": "10000"}')
FROM bic.bic_schema.CUSTOMER_OFFERINGS;

 INSERT INTO bic.bic_schema.CUSTOMER_OFFERINGS (
    CUSTOMER_ID, SITE_ID, OFFERINGS, OFFERING_PRICE, OFFERINGS_EUC, OFFERING_TYPE,
    POTENTIAL_OFFERING_LEVEL_INVESTMENT, PRODUCT_CODE, PRODUCTS_EUC, PRODUCT_UNIT_PRICE, CSA, SAVINGS)
SELECT
    'Vishal Super Market', 'BN001','KITCHEN SPECIALTY',20,COALESCE(MAX(OFFERINGS_EUC), 0) + 1,'Regular',34,
    'Super Natural Stain remover' ,COALESCE(MAX(PRODUCTS_EUC), 0) + 1,2,
    PARSE_JSON('{"Room Count": "100", "Occ. Rate": "80"}'),
    PARSE_JSON('{"Water Savings": "100", "Energy Savings": "10000"}')
FROM bic.bic_schema.CUSTOMER_OFFERINGS;  
 INSERT INTO bic.bic_schema.CUSTOMER_OFFERINGS (
    CUSTOMER_ID, SITE_ID, OFFERINGS, OFFERING_PRICE, OFFERINGS_EUC, OFFERING_TYPE,
    POTENTIAL_OFFERING_LEVEL_INVESTMENT, PRODUCT_CODE, PRODUCTS_EUC, PRODUCT_UNIT_PRICE, CSA, SAVINGS)
select * from bic.bic_schema.CUSTOMER_OFFERINGS;

delete from bic.bic_schema.CUSTOMER_OFFERINGS;

UPDATE BIC.bic_schema.CUSTOMER_OFFERINGS AS t
SET OFFERINGS_EUC = seq.seq_num
FROM (
    SELECT CUSTOMER_ID, ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS seq_num
    FROM BIC.bic_schema.CUSTOMER_OFFERINGS
) AS seq
WHERE t.CUSTOMER_ID = seq.CUSTOMER_ID;


 SELECT top 10 E.CustomerType as PRODUCT_POV, D.CustomerType, F.CustomerType, G.CustomerType, H.CustomerType, I.CustomerType, C.* FROM CUSTOMER_OFFERINGS C, 
TABLE(PRODUCT_POV(    C."CUSTOMER_ID",    C."SITE_ID",    C."OFFERINGS",
    C."OFFERING_PRICE",    C."OFFERINGS_EUC",
    C."OFFERING_TYPE", 
    C."POTENTIAL_OFFERING_LEVEL_INVESTMENT",    C."PRODUCT_CODE",
    C."PRODUCTS_EUC",    C."PRODUCT_UNIT_PRICE", 
    C."CSA"
     ) ) E,
     TABLE(PRODUCT_POV(    C."CUSTOMER_ID",    C."SITE_ID",    C."OFFERINGS",
    C."OFFERING_PRICE",    C."OFFERINGS_EUC",
    C."OFFERING_TYPE", 
    C."POTENTIAL_OFFERING_LEVEL_INVESTMENT",    C."PRODUCT_CODE",
    C."PRODUCTS_EUC",    C."PRODUCT_UNIT_PRICE", 
    C."CSA"
     ) ) F,
     TABLE(PRODUCT_POV(    C."CUSTOMER_ID",    C."SITE_ID",    C."OFFERINGS",
    C."OFFERING_PRICE",    C."OFFERINGS_EUC",
    C."OFFERING_TYPE", 
    C."POTENTIAL_OFFERING_LEVEL_INVESTMENT",    C."PRODUCT_CODE",
    C."PRODUCTS_EUC",    C."PRODUCT_UNIT_PRICE", 
    C."CSA"
     ) ) G,
     TABLE(PRODUCT_POV(    C."CUSTOMER_ID",    C."SITE_ID",    C."OFFERINGS",
    C."OFFERING_PRICE",    C."OFFERINGS_EUC",
    C."OFFERING_TYPE", 
    C."POTENTIAL_OFFERING_LEVEL_INVESTMENT",    C."PRODUCT_CODE",
    C."PRODUCTS_EUC",    C."PRODUCT_UNIT_PRICE", 
    C."CSA"
     ) ) H,
     TABLE(PRODUCT_POV(    C."CUSTOMER_ID",    C."SITE_ID",    C."OFFERINGS",
    C."OFFERING_PRICE",    C."OFFERINGS_EUC",
    C."OFFERING_TYPE", 
    C."POTENTIAL_OFFERING_LEVEL_INVESTMENT",    C."PRODUCT_CODE",
    C."PRODUCTS_EUC",    C."PRODUCT_UNIT_PRICE", 
    C."CSA"
     ) ) I,
TABLE(OFFERING_POV(
    C."CUSTOMER_ID",
    C."SITE_ID",
    C."OFFERINGS",
    C."OFFERING_PRICE",
    C."OFFERINGS_EUC",
    C."OFFERING_TYPE",   
    C."POTENTIAL_OFFERING_LEVEL_INVESTMENT", 
    C."PRODUCT_CODE",
    C."PRODUCTS_EUC",
    C."PRODUCT_UNIT_PRICE", 
    C."CSA"
     )
) D;