import org.example.model.siteOfferings;
import com.snowflake.snowpark_java.types.Variant;
import java.util.Map;

global org.example.model.CustomerType customerType;

dialect "mvel"

rule "Regular1"
    when
        $customer : siteOfferings(offerings == "KITCHEN SPECIALTY" && offeringType == "Regular") 
        
    then                
        Map obj = $customer.getCSA();

        Integer roomCount = obj.containsKey("Room Count") ? (Integer) obj["Room Count"] : 1;
        Integer occRate = obj.containsKey("Occ. Rate")  ? (Integer) obj["Occ. Rate"] : 100;
        
        customerType.setCustomerType($customer.getOfferingPrice() * roomCount * occRate);
end 
 